import fs from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";
import { foundationRoot } from "./paths.js";

export async function loadBriefing() {
  const file = path.join(foundationRoot, "registry", "briefing.yml");
  return YAML.parse(await fs.readFile(file, "utf8"));
}

export function readPath(object, dottedPath) {
  return dottedPath.split(".").reduce((value, key) => (value == null ? undefined : value[key]), object);
}

function isAnswered(value) {
  if (value === undefined || value === "") return false;
  if (Array.isArray(value)) return value.length > 0;
  return true;
}

/** Evaluates every briefing question against a project profile. */
export function evaluateBriefing(briefing, profile) {
  return briefing.sections.map((section) => ({
    ...section,
    questions: section.questions.map((question) => ({
      ...question,
      answered: isAnswered(readPath(profile, question.path))
    }))
  }));
}

export function summarizeBriefing(sections) {
  const questions = sections.flatMap((section) => section.questions);
  const openMandatory = questions.filter((question) => question.mandatory && !question.answered);
  return {
    total: questions.length,
    answered: questions.filter((question) => question.answered).length,
    openMandatory
  };
}

export function renderBriefingMarkdown(sections, projectName) {
  const lines = [
    "# Briefing · " + projectName,
    "",
    "Generated by `mgd-platform briefing --write`. Answers belong in `MGD_PLATFORM.yml`.",
    "Pflichtfragen sind mit **Pflicht** markiert. Danach `mgd-platform recommend` ausführen.",
    ""
  ];

  for (const section of sections) {
    lines.push("## " + section.title, "");
    for (const question of section.questions) {
      const box = question.answered ? "[x]" : "[ ]";
      const mandatory = question.mandatory ? " **Pflicht**" : "";
      lines.push("- " + box + " " + question.question + mandatory + " `" + question.path + "`");
    }
    lines.push("");
  }

  return lines.join("\n");
}
