import fs from "node:fs/promises";
import path from "node:path";
import { loadProjectProfile } from "../lib/profile.js";
import { validateProfile } from "../lib/validation.js";

function addFinding(findings, severity, area, message) {
  findings.push({ severity, area, message });
}

export async function auditCommand(args = []) {
  const target = args.find((arg) => !arg.startsWith("--")) || ".";
  const write = args.includes("--write");
  const root = path.resolve(target);
  const findings = [];

  let loaded;
  try {
    loaded = await loadProjectProfile(root);
  } catch (error) {
    console.error("✗ Audit requires MGD_PLATFORM.yml: " + error.message);
    return 1;
  }

  const profile = loaded.profile;
  const validation = await validateProfile(profile);

  for (const error of validation.schemaErrors) addFinding(findings, "critical", "profile", error);
  for (const error of validation.ruleErrors) addFinding(findings, "high", "profile", error);
  for (const warning of validation.warnings) addFinding(findings, "medium", "profile", warning);

  const expectedFiles = [
    ["AGENTS.md", "high", "documentation"],
    ["SECURITY.md", "medium", "security"],
    ["FEATURE-GOVERNANCE.md", "medium", "governance"]
  ];

  for (const item of expectedFiles) {
    const exists = await fs.access(path.join(root, item[0])).then(() => true).catch(() => false);
    if (!exists) addFinding(findings, item[1], item[2], item[0] + " is missing");
  }

  if (profile.infrastructure && profile.infrastructure.backup && profile.infrastructure.backup !== "none") {
    const evidenceExists = await fs.access(path.join(root, ".mgd", "evidence", "backup-tested.json")).then(() => true).catch(() => false);
    if (!evidenceExists) addFinding(findings, "high", "operations", "Backup is declared but backup-tested evidence is missing");
  }

  if (profile.security && profile.security.audit_log && !(profile.release_gates || []).includes("security-reviewed")) {
    addFinding(findings, "medium", "security", "Audit logging is enabled, but security-reviewed is not a release gate");
  }

  if (profile.features && profile.features.ai_agents && !(profile.agents && profile.agents.production_changes_require_approval)) {
    addFinding(findings, "high", "agents", "AI agents are enabled without explicit production approval requirement");
  }

  const rank = { critical: 0, high: 1, medium: 2, low: 3 };
  findings.sort((a, b) => rank[a.severity] - rank[b.severity]);

  console.log("\nMGD Platform Audit\n==================");
  console.log("Project: " + (profile.project && profile.project.name ? profile.project.name : root));
  console.log("Findings: " + findings.length);

  if (findings.length === 0) {
    console.log("\n✓ No foundation gaps detected by the current automated checks.");
  } else {
    for (const finding of findings) {
      console.log("\n[" + finding.severity.toUpperCase() + "] " + finding.area);
      console.log("  " + finding.message);
    }
  }

  if (write) {
    const lines = [
      "# MGD Platform Audit",
      "",
      "Project: **" + (profile.project && profile.project.name ? profile.project.name : path.basename(root)) + "**",
      "",
      "Generated by `mgd-platform audit --write`.",
      "",
      "## Findings",
      ""
    ];

    if (findings.length === 0) {
      lines.push("No automated foundation gaps detected.");
    } else {
      for (const finding of findings) {
        lines.push("### " + finding.severity.toUpperCase() + " · " + finding.area);
        lines.push("");
        lines.push(finding.message);
        lines.push("");
      }
    }

    const outputPath = path.join(root, "MGD_PLATFORM_AUDIT.md");
    await fs.writeFile(outputPath, lines.join("\n"), "utf8");
    console.log("\n✓ Wrote " + outputPath);
  }

  const blocking = findings.some((finding) => finding.severity === "critical" || finding.severity === "high");
  return blocking ? 1 : 0;
}
